[[thingverse-gatling-load-test]]
== Thingverse Load Tests

Before you can run load tests you would need the following.

[[thingverse-gatling-load-test-setup]]
=== Load Test Environment Setup

1.  A Gatling scenario to execute. We supply a few such scenarios.
2.  Thingverse API and Backend should be running and fully functional.
3.  Based on the Thingverse environment you would be using for the load tests, you would need to start additional services like Consul, Zuul Proxy and a Cassandra cluster.

[CAUTION]
====
You would need to carefully review the Gatling load test scenario you would be using. You must provision the right hardware abd network capacity. Also, you need to set up your services in such a way, that it can handle the load generated by your test. A load test is generally an expensive operation conducted on rented hardware/network, and you wouldn't want to incur costs for nothing.
====

[[thingverse-gatling-load-test-running]]
=== Running Load Tests

The load tests can be run in two ways. The first method is to run using Gradle.
----
$ cd thingverse-stress-tests
$ ./gradlew gatlingRun
----

Another way is to use a fat jar. The build process also produces a fat jar that can be used to run the pre-packaged scenarios. If you have the fat jar, you don't need Gradle and just need Java. Execute the following command.

----
$ java -jar thingverse-stress-tests-0.0.1-gatling.jar -s <simulation_name>
----

[NOTE]
====
You should first set the BASE_URL for the test.

----
$ set BASE_URL=http://mbp16.local:30091 <1>
$ export BASE_URL=http://mbp16.local:30091 <2>
----
<1> Windows
<1> macOS
====

You can also run using a docker image. If you don't have the image, you can build it as follows.


----
cd thingverse-stress-tests
gradle build
docker build --tag thingverse/thingverse-stress-tests .
----

Launch a container using the image.

Now run the test.
----
$ docker run --name=thingverse-stress-tests -env BASE_URL=http://localhost:8762/thingverse-api" thingverse/thingverse-stress-tests --simulation=<simulation_name> <1>

$ docker run -d --name=thingverse-stress-tests -env BASE_URL=http://localhost:8762/thingverse-api" thingverse/thingverse-stress-tests --simulation=<simulation_name> <2>
----
<1>  Launches the container interactively.
<2>  Launches the container in daemon mode and returns.

[NOTE]
====
Replace `<simulation_name>` with one of the pre-packaged simulations. You would need to specify the FQCN of the scenario e.g `BasicUnsecuredStandaloneSimulation`.
====

[[thingverse-gatling-load-test-hardware-sizing]]
=== Hardware Sizing Tips