apiVersion: v1
kind: Service
metadata:
  name: thingverse-backend
  namespace: thingverse
  labels:
    app: thingverse-backend
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: thingverse-backend