/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thingverse.logging;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = SampleLoggingApp.class)
public class SampleLoggingAppTests {

    private static final Logger LOGGER = LoggerFactory.getLogger(SampleLoggingAppTests.class);

    @Test
    public void contextLoads() {
        LOGGER.info("Context successfully loaded for SampleLoggingApp.");
    }
}

