CREATE TABLE user_table
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_name VARCHAR(32)                             NOT NULL UNIQUE,
    password  VARCHAR(128)                            NOT NULL
);
--
-- Valid roles that may be used in the system
create table role_table
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    role_name VARCHAR(32)                             NOT NULL UNIQUE
);
--
CREATE TABLE authority_table
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_name VARCHAR(32)                             NOT NULL,
    authority VARCHAR(32)                             NOT NULL,
    CONSTRAINT unique_username_authority UNIQUE (user_name, authority),
    CONSTRAINT fk_igc_authority_user_name_igc_user_user_name
        FOREIGN KEY (user_name)
            REFERENCES user_table (user_name),
    CONSTRAINT fk_igc_authority_authority_igc_role_role_name
        FOREIGN KEY (authority)
            REFERENCES role_table (role_name)
);
