apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thingverse-backend-pod-reader
  namespace: thingverse
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources:
      - pods
    verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-thingverse-backend-pods
  namespace: thingverse
subjects:
  - kind: ServiceAccount
    name: thingverse-svc-account
    namespace: thingverse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thingverse-backend-pod-reader