apiVersion: apps/v1
kind: Deployment
metadata:
  name: thingverse-api
  namespace: thingverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thingverse-api
  template:
    metadata:
      labels:
        app: thingverse-api
    spec:
      containers:
        - name: thingverse-api
          image: gcr.io/erudite-realm-266710/thingverse-api:1.0.0
          ports:
            - containerPort: 9191
              name: http
          env:
            - name: THINGVERSE_API_OPERATION_MODE
              value: "cluster"
            - name: RUNTIME_ENVIRONMENT
              value: "kubernetes"
---

apiVersion: v1
kind: Service
metadata:
  name: thingverse-api
  namespace: thingverse
spec:
  type: LoadBalancer
  selector:
    app: thingverse-api
  ports:
    - port: 30091
      targetPort: 9191

#---
#apiVersion: "networking.k8s.io/v1beta1"
#kind: Ingress
#metadata:
#  name: thingverse-api
#  namespace: thingverse
#spec:
#  rules:
#    - host: "tp1.local"
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: thingverse-api
#              servicePort: 9191