{{- if .Values.thingverse.monitoring.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus-server
{{- end }}