{{- if .Values.thingverse.cassandra.needed -}}
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  type: NodePort
  ports:
    - port: 9042
      targetPort: 9042
      nodePort: 30090
      protocol: TCP
{{- end }}