apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thingverse-backend-pod-reader
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources:
      - nodes
      - pods
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - namespaces
      - endpoints
    verbs: ["get", "list", "watch"]