apiVersion: v1
kind: Service
metadata:
  name: thingverse-backend
  labels:
    app: thingverse-backend
spec:
{{/*  clusterIP: "None"*/}}
  type: "ClusterIP"
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: thingverse-backend