apiVersion: v1
kind: Service
metadata:
  name: thingverse-api
spec:
  {{- if not .Values.thingverse.ingress.enabled }}
  type: {{ .Values.thingverse.apiApp.service.type }}
  {{- end }}
  selector:
    app: thingverse-api
  ports:
    - port: 9191
      targetPort: 9191
      {{- if not .Values.thingverse.ingress.enabled }}
      nodePort: 30091
      {{- end }}