{
 "title": "Thingverse",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Currently Active Things",
   "type": "stat",
   "description": "This panel shows the number of currently active things.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "thingverse_active_thing_count" }
   ]
  },
  {
   "title": "Total Messages Received",
   "type": "stat",
   "description": "This panel shows the total number of messages received by the Thingverse cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "thingverse_total_messages_received"
    }
   ]
  },
  {
   "title": "Average Message Age",
   "type": "graph",
   "description": "This panel shows the variation of average message age in the mailbox over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "µs", "label": "Message Age in Mailbox" }
   ],
   "targets": [
    { "expr": "thingverse_average_message_age" }
   ]
  },
  {
   "title": "HTTP Requests per second",
   "type": "graph",
   "description": "This panel shows statistics about incoming HTTP requests per second over a 5m window, categorized by uri, method, exception, stats code etc.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(thingverse_http_server_requests_seconds_count[5m])"
    }
   ]
  }
 ]
}