apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: library/consul:1.7.2
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: consul
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30085