apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_INSTALL_PLUGINS
              value: "grafana-kubernetes-app"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "grafanaadmin"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - port: 3012
      targetPort: 3000
      nodePort: 30012
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30019