apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
  namespace: thingverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: library/consul:1.7.2
          ports:
            - containerPort: 8500
---

apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: thingverse
spec:
  selector:
    app: consul
  type: LoadBalancer
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP